version: "3.8"

services:
  rabbit:
    build: rabbitmq/
    hostname: 'rabbit'
    container_name: 'rabbit'
    expose:
      - 5672
      - 15672
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:15672"]
      interval: '10s'
      timeout: '10s'
      retries: 5
    restart: on-failure
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      rabbit:
        condition: service_healthy
    restart: on-failure
  server:
    build: server/
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - minio
    restart: on-failure
  worker:
    build: worker/
    container_name: worker
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock # mac
      - //var/run/docker.sock:/var/run/docker.sock # windows
    depends_on:
      - server
    restart: on-failure